### ISSUE TITLE
python - Utiliser un requirements.txt

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra_documentation#2]
Pour l'installation des modules python, ajouter un requirements.txt (peut être généré en redirigeant la sortie d'un `pip freeze`).

ensuite, l'installation des dépendances se résumera à un:

```
pip install -r requirements.txt
```

**Comment by MaelREBOUX** [comment]
Fait avec f97665aa5a876f3a40c82c1c18d0da923e2e7d17 mais uniquement des requirements Ubuntu 20.04
Je vais rajouter ceux pour Mac OS.

J'ai de côté les wheels si besoin.

Noter que j'ai amendé la doc d'installation : e259e6e24dcd3b6c35bded3bb902ba028691ddbc
