### ISSUE TITLE
sortie pdf de la doc cadastrapp

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra_documentation#4]
pour la doc cadastrapp contenant des gif animés, j'ai du ajouter un plugin sphinx a la conf
```
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -40,6 +40,7 @@ author = 'la communauté geOrchestra'
 # extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
 # ones.
 extensions = [
+'sphinx.ext.imgconverter'
 ]
```
+ `apt install imagemagick` afin que sphinx puisse trouver `convert` et convertir les gif en png (en gardant uniquement la première image)

enfin pour une sortie pdf via `make latexpdf` les dépendances (pour moi sur debian bullseye) étaient:
- texlive-latex-base
- latexmk
- texlive
- texlive-lang-french
- texlive-science
- texlive-pstricks
- texlive-formats-extra

**Comment by MaelREBOUX** [comment]
fermeture cause passage à mkdocs
