### ISSUE TITLE
Créer une table des matières dans chaque sommaire des guides

### ISSUE THREAD

**Issue by MarieSuet** [georchestra/georchestra_documentation#7]
Pour créer la table des matières, normalement le langage markdown est de ce style :

# Table of contents
1. [Introduction](#introduction)
2. [Some paragraph](#paragraph1)
    1. [Sub paragraph](#subparagraph1)
3. [Another paragraph](#paragraph2)

## This is the introduction <a name="introduction"></a>
Some introduction text, formatted in heading 2 style

## Some paragraph <a name="paragraph1"></a>
The first paragraph text

### Sub paragraph <a name="subparagraph1"></a>
This is a sub paragraph, formatted in heading 3 style

## Another paragraph <a name="paragraph2"></a>
The second paragraph text

**Comment by MarieSuet** [comment]
https://stackoverflow.com/questions/11948245/markdown-to-create-pages-and-table-of-contents

**Comment by MaelREBOUX** [comment]
Autres pistes :
- https://pypi.org/project/mkdocs-toc-md/
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#table-of-contents

**Comment by jeanmi151** [comment]
j'ai testé mkdocs-toc-md, c'est pas tout a fait ce que l'on veut mais il y aurai peu être un petit hack a faire (pseudo manuel)

**Comment by jeanmi151** [comment]
Testé mais pas 100% validé (copier coller à faire) : https://github.com/georchestra/georchestra_documentation#tableofcontent
