### ISSUE TITLE
Créer la page d'accueil HTML de https://docs.georchestra.org/

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/georchestra_documentation#8]
Selon Agathe (si j'ai bien compris) : pompage de choses depuis le site www actuel et bootstrap

**Comment by MaelREBOUX** [comment]
1er jet avec https://github.com/georchestra/georchestra_documentation/commit/5cf7f726e83326d43e4a7110e04f40161a51d792

MAIS reste à peaufiner. Donc on laisse ouvert.

Notamment : organisation autour de MapStore2.

**Comment by gryckelynck** [comment]
Sur la page d'accueil, je propose que l'ensemble du bloc d'un module soit cliquable plutôt que juste la description.
Concrètement, passer de:
![image](https://user-images.githubusercontent.com/3984125/217822517-34d1c0dd-2049-4eb0-9144-f4ba65d4e571.png)

A 
![image](https://user-images.githubusercontent.com/3984125/217822560-d264f3dc-709a-4ba0-bfb9-afe384e8a209.png)

**Comment by gryckelynck** [comment]
Pour l'organisation autour de MapStore2 et des plugins à documenter, voici une piste de réflexion: au survol ou clic sur le bloc principal, ouverture d'un sous-niveau (via classe collapse de Bootstrap).
(ceci n'est qu'un test: icons, couleurs, mise en forme à retravailler)
A discuter dans un ticket spécifique?

![image](https://user-images.githubusercontent.com/3984125/217828757-4f4aaa2c-5401-4f64-a3a8-05415fc0984b.png)

**Comment by MaelREBOUX** [comment]
J'adhère totalement et c'est… totalement raccord avec les échanges lors du hackaton :D

Tu peux proposer du code sous la forme d'une PR ?

**Comment by gryckelynck** [comment]
Fait via: https://github.com/georchestra/georchestra_documentation/commit/c3f44e2da81f7e67cae7bbb56f9bcf26be1058fa, https://github.com/georchestra/georchestra_documentation/commit/a2df4649cad534df4a1e2f62151a77293614ccfd et https://github.com/georchestra/georchestra_documentation/commit/c63006ac33f40f0d6ddbe2007a4e2d6014d0a37c

**Comment by gryckelynck** [comment]
Il faudrait aussi adapter les icons de chaque module MapStore (des idées ?) et les liens vers les documentations quand elles seront initiées.

**Comment by MaelREBOUX** [comment]
C'est en ligne ! Merci @gryckelynck

**Comment by MaelREBOUX** [comment]
> Il faudrait aussi adapter les icons de chaque module MapStore (des idées ?) et les liens vers les documentations quand elles seront initiées.

Oui. Je ne sais pas comment traiter ça : on a dit sur une ligne à part je crois ?
Tu peux déjà pointer cadastrapp et urbanisme.

**Comment by gryckelynck** [comment]
> Oui. Je ne sais pas comment traiter ça : on a dit sur une ligne à part je crois ?
> Tu peux déjà pointer cadastrapp et urbanisme.

Je ne comprends pas bien...
"une ligne à part" => c'est fait il me semble avec https://github.com/georchestra/georchestra_documentation/commit/a2df4649cad534df4a1e2f62151a77293614ccfd. Si on parle de la même chose : quand on clique sur le bloc MapStore, on a un sous-menu sur une ligne qui s'affiche (note: responsive à tester je ne suis pas certain que ce que j'ai fait fonctionne dans tous les cas de figure).
Concernant les icons, j'ai bêtement copié l'icon de DataFeeder. Ma question: faut-il prévoir des icons spécifiques pour chaque module ? 
Au passage, quelle est la source des autres icons ?

**Comment by MaelREBOUX** [comment]
bonjour @gryckelynck puis-je fermer ce ticket ?

**Comment by gryckelynck** [comment]
Oui c'est bon de mon côté.
